apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
