apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bggbackend-deploy
  namespace: bggns
  labels:
    app: bgg
    tier: backend
    name: bggbackend-po
spec:
  selector:
    matchLabels:
      app: bgg
      tier: backend
      name: bggbackend-po
  replicas: 3
  template:
    metadata:
      labels:
        app: bgg
        tier: backend
        name: bggbackend-po
    spec:
      containers:
      - name:  bggbackend
        image:  stackupiss/bgg-backend:v1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        envFrom:
          - configMapRef:
              name: bgg-cm
          - secretRef:
              name: bgg-secret
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
spec:
  selector:
    app: bgg
    tier: backend
    name: bggbackend-po
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
