---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bggdb-deploy
  namespace: bggns
  labels:
    app:  bgg
    tier: db
spec:
  selector:
    matchLabels:
        app: bgg
        tier: db
        name: bggdb-po
  replicas: 1
  template:
    metadata:
      labels:
        app: bgg
        tier: db
        name: bggdb-po
    spec:
      containers:
      - name:  bggdb
        image:  stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  selector:
    app:  bgg
    tier: db
    name: bggdb-po
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
