---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
type: Opaque
data:
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
data:
  MINIO_ROOT_USER: user
